# Generated by Django 3.1.6 on 2021-07-01 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='contacto_principal',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no seguinte formato: +9999999. Deve conter no maximo 12 digitos', regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='contacto_secúndario',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no seguinte formato: +9999999. Deve conter no maximo 12 digitos', regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
