# Generated by Django 3.1.6 on 2021-07-01 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousesApp', '0002_auto_20210701_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='contacto_principal',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no seguinte formato: +999999999999. Deve conter no maximo 15 digitos', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='contacto_secúndario',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no seguinte formato: +999999999999. Deve conter no maximo 15 digitos', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
