# Generated by Django 3.2.5 on 2021-07-22 10:31

import HousesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousesApp', '0003_auto_20210701_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='meses_adiantados',
            field=models.IntegerField(default=1, validators=[HousesApp.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='numero_de_divisoes',
            field=models.IntegerField(validators=[HousesApp.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='preço',
            field=models.FloatField(default=0.0, validators=[HousesApp.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='houselistingpicture',
            name='descriçao',
            field=models.CharField(choices=[('living_room', 'Sala de Estar'), ('dining_room', 'Sala de Jantar'), ('kitchen', 'Cozinha'), ('bedroom', 'Quarto'), ('main_bedroom', 'Quarto Principal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='houselistingpicture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
