# Generated by Django 3.2.5 on 2021-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HousesApp', '0004_auto_20210722_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselistingpicture',
            name='descriçao',
            field=models.CharField(choices=[('main_bedroom', 'Quarto Principal'), ('bedroom', 'Quarto'), ('living_room', 'Sala de Estar'), ('dining_room', 'Sala de Jantar'), ('kitchen', 'Cozinha'), ('bathroom', 'Quarto de Banho')], max_length=20),
        ),
    ]
