# Generated by Django 3.2.5 on 2021-07-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HousesApp', '0006_rename_descriçao_houselistingpicture_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Quarto Principal', 'Quarto Principal'), ('Quarto', 'Quarto'), ('Sala de Estar', 'Sala de Estar'), ('Sala de Jantar', 'Sala de Jantar'), ('Cozinha', 'Cozinha'), ('Quarto de Banho', 'Quarto de Banho')], max_length=20)),
                ('foto', models.ImageField(upload_to='images/houses')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='HousesApp.houselisting')),
            ],
        ),
        migrations.DeleteModel(
            name='HouseListingPicture',
        ),
    ]
